# ** Preview tasks**

Import numpy and pandas

In [ ]:
import numpy as np

In [7]:
import pandas as pd

# **Question # 1** 

The version of numpy is:

In [9]:
print(np.__version__)

1.18.1


# ** Question # 2**

The version of pandas is:

In [10]:
print (pd.__version__)

1.0.1


## Getting the data

In [49]:
df = pd.read_csv(
    "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv")

          Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driv

Visualization of df:

In [15]:
df.head(5)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

I create a copy of df named df2. Then I will work on df2.

In [52]:
df2=df.copy()

# **Question # 3**

In [ ]:
Mean of BMW prices:

In [53]:
df2[df2["Make"]=="BMW"].MSRP. mean()

61546.76347305389

if we need to know the mean for each make, this is:

In [63]:
df.groupby(['Make']).MSRP. mean()

Make
Acura            3.488759e+04
Alfa Romeo       6.160000e+04
Aston Martin     1.979104e+05
Audi             5.345211e+04
BMW              6.154676e+04
Bentley          2.471693e+05
Bugatti          1.757224e+06
Buick            2.820661e+04
Cadillac         5.623132e+04
Chevrolet        2.835039e+04
Chrysler         2.672296e+04
Dodge            2.239006e+04
FIAT             2.267024e+04
Ferrari          2.382188e+05
Ford             2.739927e+04
GMC              3.049330e+04
Genesis          4.661667e+04
HUMMER           3.646441e+04
Honda            2.667434e+04
Hyundai          2.459704e+04
Infiniti         4.239421e+04
Kia              2.531017e+04
Lamborghini      3.315673e+05
Land Rover       6.782322e+04
Lexus            4.754907e+04
Lincoln          4.283983e+04
Lotus            6.918828e+04
Maserati         1.142077e+05
Maybach          5.462219e+05
Mazda            2.003938e+04
McLaren          2.398050e+05
Mercedes-Benz    7.147623e+04
Mitsubishi       2.124054e+04
Nissa

# ** Question # 4  **

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?. Results: 

In [54]:
df2[df2["Year"]>=2015]["Engine HP"].isna().sum()

51

# ** Question # 5 **

Calculate the average "Engine HP" in the dataset and round.

In [58]:
 mean_hp_before=round (df2["Engine HP"].mean())
print (mean_hp_before)

249


Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
Now, calcualte the average of "Engine HP" again, using round:

In [60]:
mean_hp_after =round (df2["Engine HP"].fillna(mean_hp_before).mean())
print (mean_hp_after)

249


The average in both is the same. We have expected that result.

# ** Question # 6 **

Select all the "Rolls-Royce" cars from the dataset. With columns "Engine HP", "Engine Cylinders", "highway MPG", and eliminate duplicates:

In [69]:
df3=df2[df2["Make"]=="Rolls-Royce"][["Engine HP", "Engine Cylinders", "highway MPG"]].drop_duplicates()
df3

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

## Get the underlying NumPy array. Let's call it X: 

In [73]:
X=df3.to_numpy()
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

## Calculate XTX:

In [78]:
XTX=np.dot(X.T,X)
print (XTX)

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]


## Inverse of XTX

In [82]:
inv_XTX=np.linalg.inv(XTX)
inv_XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

Vertification: I do the product between XTX and inv_XTX, we expect [I]

In [84]:
Verification=np.dot(inv_XTX, XTX)
print (Verification)

[[ 1.00000000e+00 -1.73472348e-18  8.21391566e-16]
 [ 1.84297022e-13  1.00000000e+00  1.39888101e-14]
 [-3.60211860e-13 -1.58206781e-14  1.00000000e+00]]


## Sum elements of inv XTX

In [85]:
print(np.sum(inv_XTX))

0.032212320677486195


# ** Question # 7 **

In [88]:
y=np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [89]:
w=np.dot(np.dot(inv_XTX,np.transpose(X)),y)
print (w)

[ 0.19989598 31.02612262 31.65378877]


The value of first element of W is 0.19989 (aprox 0.2)